apiVersion: v1
kind: Pod
metadata:
  name: pod-user
spec:
  containers:
  - image: lemena86/udacity-restapi-user
    name: udacity-restapi-user
    imagePullPolicy: Always          
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"       
    ports:
    - containerPort: 8080
  restartPolicy: Always